# Generated by Django 4.1 on 2023-03-15 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
            ],
        ),
    ]
