# Generated by Django 4.1 on 2023-12-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
    ]
