# Generated by Django 4.1 on 2023-03-15 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pesquisador', '0003_alter_pesquisador_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(default=datetime.date.today, verbose_name='Data de entrada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Pesquisador.pesquisador')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000, verbose_name='Título')),
                ('descrição', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(default=datetime.date.today, verbose_name='Data de fim')),
                ('participantes', models.ManyToManyField(through='Projeto.Participacao', to='Pesquisador.pesquisador')),
            ],
        ),
        migrations.AddField(
            model_name='participacao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Projeto.projeto'),
        ),
    ]
