# Generated by Django 4.1 on 2023-03-15 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_fim',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de início'),
        ),
    ]
