# Generated by Django 4.1 on 2023-03-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0002_projeto_data_fim_alter_projeto_data_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
