# Generated by Django 4.1 on 2023-12-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0004_areapesquisa_areaspesquisaprojeto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areapesquisa',
            options={'verbose_name': 'Área de pesquisa', 'verbose_name_plural': 'Áreas de pesquisa'},
        ),
        migrations.AlterModelOptions(
            name='areaspesquisaprojeto',
            options={'verbose_name': 'Área de pesquisa de projeto', 'verbose_name_plural': 'Áreas de pesquisa de projetos'},
        ),
        migrations.AlterModelOptions(
            name='participacao',
            options={'verbose_name': 'Participação em projeto', 'verbose_name_plural': 'Participações em projetos'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
