# Generated by Django 4.1 on 2024-01-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0005_alter_areapesquisa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areapesquisa',
            name='foto',
            field=models.ImageField(blank=True, default='areas_pesquisa/fotos/default.png', null=True, upload_to='areas_pesquisa/fotos/'),
        ),
    ]
