# Generated by Django 4.1 on 2024-01-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0006_areapesquisa_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='foto',
            field=models.ImageField(blank=True, default='pesquisadores/fotos/default.png', null=-1, upload_to='projetos/fotos/'),
            preserve_default=-1,
        ),
        migrations.AlterField(
            model_name='areapesquisa',
            name='foto',
            field=models.ImageField(default='pesquisadores/fotos/default.png', upload_to='areas_pesquisa/fotos/'),
        ),
    ]
