# Generated by Django 4.1 on 2023-03-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Professor'), ('2', 'Pesquisador'), ('3', 'Aluno de pós-graduação'), ('4', 'Aluno de IC'), ('5', 'Estagiário'), ('6', 'Outro')], max_length=2, verbose_name='Tipo de pesquisador')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contato', models.CharField(max_length=20, verbose_name='Contato')),
                ('instituicao', models.CharField(max_length=50, verbose_name='Instituição')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('curso', models.CharField(max_length=50, verbose_name='Curso')),
                ('area_pesquisa', models.CharField(max_length=200, verbose_name='Área de pesquisa')),
                ('descricao_pesquisador', models.TextField(verbose_name='Descrição do pesquisador')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
    ]
