# Generated by Django 4.1 on 2023-03-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesquisador',
            old_name='status',
            new_name='ativo',
        ),
    ]
