# Generated by Django 4.1 on 2023-03-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0003_alter_pesquisador_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='genero',
            field=models.CharField(choices=[('1', 'Feminino'), ('2', 'Masculino'), ('3', 'Outro')], default=1, max_length=1, verbose_name='Gênero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='titulacao',
            field=models.CharField(choices=[('1', 'Doutorado completo'), ('2', 'Mestrado completo'), ('3', 'Graduação completa'), ('4', 'Graduação em andamento')], default=2, max_length=1, verbose_name='Contato'),
            preserve_default=False,
        ),
    ]
