# Generated by Django 4.1 on 2023-12-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0004_pesquisador_genero_pesquisador_titulacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesquisador',
            options={'verbose_name': 'Pesquisador', 'verbose_name_plural': 'Pesquisadores'},
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='foto',
            field=models.ImageField(blank=True, default='pesquisadores/foto/deafult.png', null=True, upload_to='pesquisadores/foto/'),
        ),
    ]
