# Generated by Django 4.1 on 2023-12-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0005_alter_pesquisador_options_pesquisador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='foto',
            field=models.ImageField(blank=True, default='pesquisadores/foto/default.png', null=True, upload_to='pesquisadores/foto/'),
        ),
    ]
