# Generated by Django 4.1 on 2024-01-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0006_alter_pesquisador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='foto',
            field=models.ImageField(blank=True, default='pesquisadores/fotos/default.png', null=True, upload_to='pesquisadores/fotos/'),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='titulacao',
            field=models.CharField(choices=[('1', 'Doutorado completo'), ('2', 'Mestrado completo'), ('3', 'Graduação completa'), ('4', 'Graduação em andamento')], max_length=1, verbose_name='Titulação'),
        ),
    ]
