# Generated by Django 4.1 on 2023-03-15 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pesquisador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000, verbose_name='Título')),
                ('ano', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2200), django.core.validators.MinValueValidator(1900)], verbose_name='Ano da publicação')),
                ('publicacao', models.CharField(max_length=1000, verbose_name='Publicação')),
                ('palavras_chave', models.CharField(max_length=1000, verbose_name='Palavras-chave')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('abstract', models.TextField(verbose_name='Abstract')),
                ('link', models.URLField(verbose_name='Link da publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Autor_artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Artigo.artigo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Pesquisador.pesquisador')),
            ],
        ),
    ]
