# Generated by Django 4.1 on 2023-03-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesquisador', '0003_alter_pesquisador_ativo'),
        ('Artigo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='autores',
            field=models.ManyToManyField(to='Pesquisador.pesquisador'),
        ),
        migrations.DeleteModel(
            name='Autor_artigo',
        ),
    ]
