# Generated by Django 4.1 on 2023-12-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artigo', '0002_artigo_autores_delete_autor_artigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
    ]
